### ISSUE TITLE
Unable to Update to Newest Version

### ISSUE THREAD

**Issue by MyMediaMagnet** [loganmarchione/nginxbuild#1]
After running the bash script, I get the following at the end of the messages.

```
./configure: error: no /usr/local/src/ngx_pagespeed-release-1.12.34.1-beta/config was found
make: *** No rule to make target 'build', needed by 'default'.  Stop.
make: *** No rule to make target 'install'.  Stop.
```

Any ideas?

**Comment by loganmarchione** [comment]
I moved away from the script, so I haven't been actively updating it. What distribution are you using? Can you copy/paste the entire script here?

**Comment by MyMediaMagnet** [comment]
After trying to debug this for a while, I believe the issue is while trying to grab the psol link.  The logs show that it's getting a 404 error.  I changed some things around from your original script to try and line it up with the build instructions at the following link, but still haven't been able to get it to find the psol link.  https://modpagespeed.com/doc/build_ngx_pagespeed_from_source

```
#!/bin/bash

## This script should be run as root, since it's compiling software from source

## Set some variables
DIRECTORY=/usr/local/src
PAGESPEED_VERSION=1.12.34.1
HEADERS_VERSION=0.31
NGINX_VERSION=1.11.3

## create group and user
addgroup www-data
useradd -c www-data -d /var/www -M -g www-data -s /usr/sbin/nologin www-data

## Get PageSpeed
cd ${DIRECTORY}
wget https://github.com/pagespeed/ngx_pagespeed/archive/v${PAGESPEED_VERSION}-beta.zip
unzip v${PAGESPEED_VERSION}-beta.zip
rm v${PAGESPEED_VERSION}-beta.zip
cd ngx_pagespeed-${PAGESPEED_VERSION}-beta/
psol_url=https://dl.google.com/dl/page-speed/psol/${PAGESPEED_VERSION}.tar.gz
[ -e scripts/format_binary_url.sh ] && psol_url=$(scripts/format_binary_url.sh PSOL_BINARY_URL)
wget ${psol_url} #returns 404
tar -xzvf $(basename ${psol_url})  # extracts to psol/
rm ${PAGESPEED_VERSION}.tar.gz
```

**Comment by loganmarchione** [comment]
I'm seeing the same thing, getting a 404 error on this link.  
https://dl.google.com/dl/page-speed/psol/1.12.34.1.tar.gz

This seems to be the oldest link that works. They must not be updating their server.  
https://dl.google.com/dl/page-speed/psol/1.11.33.4.tar.gz

**Comment by MyMediaMagnet** [comment]
I'm interested.  Is there a reason you've stopped using this script?  Did you not find pagespeed to be useful?

**Comment by MyMediaMagnet** [comment]
Using the old psol script doesn't seem to make a different, and it allowed me to update to the newest version.  Here is the working code if you're interested.
```
## Get PageSpeed
cd ${DIRECTORY}
wget https://github.com/pagespeed/ngx_pagespeed/archive/v${PAGESPEED_VERSION}-beta.zip
unzip v${PAGESPEED_VERSION}-beta.zip
rm v${PAGESPEED_VERSION}-beta.zip
cd ngx_pagespeed-${PAGESPEED_VERSION}-beta/
psol_url=https://dl.google.com/dl/page-speed/psol/1.11.33.3.tar.gz
[ -e scripts/format_binary_url.sh ] && psol_url=$(scripts/format_binary_url.sh PSOL_BINARY_URL)
wget ${psol_url}
tar -xzvf $(basename ${psol_url})  # extracts to psol/
rm ${PAGESPEED_VERSION}.tar.gz
```

**Comment by loganmarchione** [comment]
No, I didn't find that pagespeed really optimized anything. I was better off implementing caching instead. Also, I found the compile flags for nginx have been changing and the script would bomb out, so I couldn't reliably run it from cron. But I'm glad you've got it working!
